# Generated by Django 4.2.5 on 2023-09-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='num_phone',
        ),
    ]
